### ISSUE TITLE
.compile() and Caching

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer-consolidate#1]
Consolidate takes {cache: true} as a way to cache the results. We should do that for .compile(), or something.

**Comment by tunnckoCore** [comment]
What's the problem to pass cache as option currently? I can't see it or i'm missing something?
I think it will "just work", currently, but it's interesting how to test it with `test-jstransformer`.

**Comment by ForbesLindesay** [comment]
@tunnckoCore I think what @RobLoach is suggesting is that we have the `.compile` endpoint return something that automatically adds `{cache: true}`, on the grounds that if you're using `.compile` instead of `.render` you probably wanted to do some kind of caching.

@RobLoach Unfortunately, this won't work because consolidate gives us no way to invalidate the internal cache stored by these modules.  Our API assumes that every time you call `.compileFile`, the files are read from disk afresh, and that you can therefore invalidate the cache by simply discarding your compiled function and generating a new one.  If people really want this behaviour, they can enable it manually as @tunnckoCore suggests.
